# Generated by Django 6.0.2 on 2026-03-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_friendship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
    ]
