# Generated by Django 6.0.2 on 2026-03-19 08:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_friendship_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('creator', 'friend')},
        ),
    ]
